# fly.toml app configuration file generated for njdealsandclicks-backend on 2025-06-30T16:01:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'njdealsandclicks-backend'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  SPRING_PROFILES_ACTIVE = 'prod'
  SERVER_ADDRESS = '0.0.0.0'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    hard_limit = 20
    soft_limit = 10

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
