app = "njdealsandclicks-backend"
primary_region = "fra"  # Puoi cambiare: fra = Francoforte, cdg = Parigi, lhr = Londra

[build]
  dockerfile = "Dockerfile"

[env]
  SPRING_PROFILES_ACTIVE = "prod"

[http_service]
  internal_port = 8080  # deve combaciare con quella esposta nel Dockerfile
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
